# src/agent2.py

from src.embedding import get_embedding
from src.search import search
from src.summarization import generate_summary_local

def retrieve_and_summarize(query: str, data, index, top_k: int = 3) -> str:
    """
    Given a query, retrieve the most relevant news articles from the preprocessed data
    and generate a concatenated summary of their short descriptions.
    
    Parameters:
        query (str): The user query.
        data (pandas.DataFrame): The preprocessed news dataset.
        index (faiss.Index): The FAISS index built over article embeddings.
        top_k (int): Number of articles to retrieve.
    
    Returns:
        str: A combined summary string generated by summarizing the retrieved articles.
    """
    # Generate an embedding for the query.
    query_embedding = get_embedding(query)
    
    # Retrieve the top_k relevant articles based on their embeddings.
    indices, distances = search(index, query_embedding, top_k)
    
    summaries = []
    # Loop through retrieved article indices.
    for idx in indices[0]:
        article = data.iloc[idx]
        short_description = article.get("short_description", "")
        
        # Generate a summary for the article's short description.
        summary = generate_summary_local(short_description)
        summaries.append(summary)
    
    # Combine the summaries (this can be refined—e.g., choose the most relevant or merge intelligently).
    combined_summary = " ".join(summaries)
    return combined_summary
